# _config.yml

title: Your Awesome Blog
email: [eugine0523@gmail.com,
finedust0523@postech.ac.kr]
description: >-
  Archive for almost everything.
baseurl: ""
url: "https://dldbwns23.github.io"
github_username: dldbwns23

# 테마 설정
theme: minima

# 플러그인 설정 (GitHub Pages에서 지원하는 플러그인)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 기본값 설정 (모든 포스트에 기본 태그를 부여)
defaults:
  - scope:
      path: ""
      type: posts # 'post'가 아닌 'posts'
    values:
      tags: [Other] # ★★★ 수정됨: 'Other'를 배열 형식인 [Other]로 변경


